[package]
name = "worktable"
version = "0.1.1"
edition = "2021"
authors = ["PathScale"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# error
eyre = "0.6.8"
# tokio
tokio = { version = "1", features = ["full"] }
# tracing
tracing = "0.1"
# serialize
serde = { version = "1", features = ["derive"] }
serde_json = "1"
csv = "1.3"
