[workspace]
members = ["codegen", "performance_measurement",  "performance_measurement/codegen"]

[package]
name = "worktable"
version = "0.3.3"
edition = "2021"
authors = ["PathScale"]

[features]
perf_measurements = ["dep:performance_measurement", "dep:performance_measurement_codegen"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6"
derive_more = { version = "1.0.0", features = ["from", "error", "display"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
smart-default = {version = "0.7.1"}
rkyv = {version = "0.7.42"}
csv = "1"
once_cell = { version = "1.19.0"}
lockfree = { version = "0.5.1"}
worktable_codegen = {path = "codegen"}
scc = "2.1.16"
futures = "0.3.30"

performance_measurement_codegen = {path = "performance_measurement/codegen", optional = true}
performance_measurement = {path = "performance_measurement", optional = true}
