[workspace]
members = ["codegen", "performance_measurement",  "performance_measurement/codegen"]

[package]
name = "worktable"
version = "0.3.0"
edition = "2021"
authors = ["PathScale"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6"
derive_more = { version = "1.0.0", features = ["from", "error", "display"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
smart-default = {version = "0.7.1"}
rkyv = {version = "0.7.45"}
csv = "1"
once_cell = { version = "1.19.0"}
lockfree = { version = "0.5.1"}
performance_measurement_codegen = {path = "performance_measurement/codegen"}
performance_measurement = {path = "performance_measurement"}
