[package]
name = "worktable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# error
eyre = "0.6.11"
# tokio
tokio = { version = "1.35.1", features = ["full"] }
# tracing
tracing = "0.1.40"
# serialize
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
csv = "1.2.1"
