[package]
name = "worktable_codegen"
version = "0.1.0"
edition = "2021"

[lib]
name = "worktable_codegen"
path = "src/lib.rs"
proc-macro = true

[dependencies]
rkyv = {version = "0.7.45"}
syn = { version = "2.0.74"}
quote = "1.0.36"
proc-macro2 = "1.0.86"
regex = "1.10.6"
convert_case = "0.6.0"